### ISSUE TITLE
Would you approve this page?

### ISSUE THREAD

**Issue by Ninja232323** [hikari-no-yume/app-compatibility-db#4]
https://appdb.touchhle.org/apps/82?show_unapproved=1

[link to pirated content removed]

**Comment by hikari-no-yume** [comment]
* This is not a support forum for the app compatibility database.
* You made this report less than 24 hours ago. If you're making this issue to try to make me approve stuff quicker, please don't. I don't want to have to check new reports more than once per day.
* Do not link to pirated content. This is your first and only warning.
